### PR TITLE
Sign-in page

### PR DESCRIPTION
**Pull request by wzhengg**
It's missing our RANIA logo and the Google logo for now. We can add those later.

### CODE REVIEW

**Review by kerryran — DISMISSED** [review]
great

**Review by sarthbpatel — COMMENTED** [review]
When highlighting the text, "We'll email you a magic link for a password-free sign-in." the text almost gets merged with the highlight color. It is a minor change. It is not required to change but is recommended. I can still merge it without changes. Let me know.

**Review by sarthbpatel — COMMENTED** [review]
When the text is inserted into the email input field, the text color is also bright. Please make the text color darker.

**Comment by wzhengg** [comment]
> When the text is inserted into the email input field, the text color is also bright. Please make the text color darker.

fixed

**Comment by wzhengg** [comment]
> When highlighting the text, "We'll email you a magic link for a password-free sign-in." the text almost gets merged with the highlight color. It is a minor change. It is not required to change but is recommended. I can still merge it without changes. Let me know.

What's your suggestion to fix this? Change the highlight color or change the text color?

**Comment by sarthbpatel** [comment]
> > When highlighting the text, "We'll email you a magic link for a password-free sign-in." the text almost gets merged with the highlight color. It is a minor change. It is not required to change but is recommended. I can still merge it without changes. Let me know.
> 
> What's your suggestion to fix this? Change the highlight color or change the text color?

**Comment by sarthbpatel** [comment]
> > When highlighting the text, "We'll email you a magic link for a password-free sign-in." the text almost gets merged with the highlight color. It is a minor change. It is not required to change but is recommended. I can still merge it without changes. Let me know.
> 
> What's your suggestion to fix this? Change the highlight color or change the text color?

I would say change the highlight color

**Review by sarthbpatel — COMMENTED** [review]
The text box inside the input field is not wide enough. When I type an email address, the box is too short to display the whole email at once. When typing, the beginning of the email gets covered or hidden 

image

The email I used to test is: 
test12345.rania@gmail.com

**Comment by wzhengg** [comment]
> The text box inside the input field is not wide enough. When I type an email address, the box is too short to display the whole email at once. When typing, the beginning of the email gets covered or hidden
> 
> image
> 
> The email I used to test is: [test12345.rania@gmail.com](mailto:test12345.rania@gmail.com)

nice catch! fixed now

**Review by sarthbpatel — APPROVED** [review]

**Review by sarthbpatel — APPROVED** [review]

**Pull request merged**
